[test]
type = google cloud storage
location = asia-south1
token = {"access_token":"ya29.A0AS3H6Ny6mc0OFZbLcXfjlhI0kUEyKvcMgK44eRc5XZB6OvzVpFRvqv5jsvtDPHgr3PF8EFZZfc5MBlPTw70OwmW9G0bQgrdmpS-C_QJIxctWSgS3ZR9YxyfgBAAkcc_S2OpcWg7KDCpOfDsTm66hNTIajs92upxwPm--kdoh2oRHhl-oncXZF803jUehfUiJupWBHM8aCgYKAbISAQ0SFQHGX2MiJSDq8RbD4ku2RevLwAPa6A0206","token_type":"Bearer","refresh_token":"1//0gic4gdpRQ2fzCgYIARAAGBASNwF-L9IrRutiiZoi4dEGfxYTUN_TShTh_bECTrAAA7JfemwtdRPmOkmy4y2Ye983pfqEcfvuCVc","expiry":"2025-07-31T22:52:50.0805804+05:30"}

